apiVersion: v1
kind: Service
metadata:
  name: sqld-backend
  namespace: db
spec:
  selector:
    app: sqld-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
