-- Replace BACKEND_DB_ROLE with the POSTGRES_USER used by sqld-backend.
-- Do not grant these privileges to PUBLIC.

GRANT USAGE ON SCHEMA ai TO BACKEND_DB_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA ai TO BACKEND_DB_ROLE;
GRANT USAGE, SELECT
    ON ALL SEQUENCES IN SCHEMA ai TO BACKEND_DB_ROLE;

ALTER DEFAULT PRIVILEGES IN SCHEMA ai
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO BACKEND_DB_ROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai
    GRANT USAGE, SELECT ON SEQUENCES TO BACKEND_DB_ROLE;
